name: benolilab-docker
secrets:
    plex_claim:
        file: ./secrets/.plex_claim    
services:   
    plex:
        container_name: plex
        image: linuxserver/plex
        networks:
          server_net:
            ipv4_address: 172.18.0.13
        ports:
            - "32400:32400/tcp"
        restart: unless-stopped
        environment:
            - TZ=America/New_York
            #GET CLAIM FROM https://www.plex.tv/claim/
            - PLEX_CLAIM=/run/secrets/plex_claim
            - PUID=1000
            - PGID=1000
        volumes:
            - plex_server_config:/config
            - plex_server_transcode:/transcode
            - plex_server_media:/data
            - /mnt/naspool:/naspool
            - /mnt/sdb:/localmedia
        devices:
            - /dev/bus/usb:/dev/bus/usb	
            - /dev/dvb:/dev/dvb
        healthcheck:
              test: "curl --connect-timeout 15 --max-time 100 --silent --show-error --fail 'http://localhost:32400/identity' >/dev/null"
              interval: 1m
              timeout: 15s
              retries: 3
              start_period: 1m
        secrets:
            - plex_claim
        labels:
            description: "Plex organizes video, music and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices."
            com.centurylinklabs.watchtower.enable: "true"
    nginx-proxy:
        container_name: nginx-proxy
        environment:
          - "DB_SQLITE_FILE=/config/database.sqlite"
          - "DISABLE_IPV6=true"
        image: "jc21/nginx-proxy-manager:latest"
        networks:
          server_net:
            ipv4_address: 172.18.0.254
        ports:
           - '80:80'
           - '443:443'
           - '81:81'
           - '853:853'
        restart: "unless-stopped"
        volumes:
          - "nginx_proxy_config:/config"
          - "nginx_proxy_letsencrypt:/etc/letsencrypt"
          - "nginx_proxy_data:/data"
        labels:
            description: "Nginx, pronounced 'engine-x,' is a versatile open-source software that acts as a web server, reverse proxy, load balancer, and more."
            com.centurylinklabs.watchtower.enable: "true"
            docker-volume-backup.stop-during-backup: "true"
        healthcheck:
          test: ["CMD", "/bin/check-health"]
          interval: 10s
          timeout: 3s
    adguardhome:
        container_name: adguardhome
        image: adguard/adguardhome
        networks:
          server_net:
            ipv4_address: 172.18.0.253
        volumes:
          - adguard_work:/opt/adguardhome/work
          - adguard_conf:/opt/adguardhome/conf
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "67:67/udp"
          - "68:68/udp"
          - "8080:80/tcp"
          - "4443:443/tcp"
          - "8853:853/tcp"
          - "3000:3000/tcp"
        restart: unless-stopped
        labels:
            description: "AdGuard Home is a network-wide ad and tracker blocker that can be deployed using Docker."
            com.centurylinklabs.watchtower.enable: "true"
        healthcheck:
            test: ["CMD-SHELL", "wget --spider -q http://localhost:3000 || exit 1"]
            interval: 10s
            timeout: 30s
            retries: 3
    syncthing:
        container_name: syncthing
        image: lscr.io/linuxserver/syncthing:latest
        networks:
          server_net:
            ipv4_address: 172.18.0.15
        hostname: syncthing # optional
        environment:
          - PUID=1001 # match with syncthinguser - see vmdocker.md
          - PGID=1001 # match with syncthinguser
          - TZ=Etc/UTC
        volumes:
          - syncthing_config:/config
          - /mnt/naspool/benolilab-docker/syncthingdata:/syncthingdata
        ports:
          - 8384:8384
          - 22000:22000/tcp
          - 22000:22000/udp
          - 21027:21027/udp
        restart: unless-stopped
        labels:
            description: "Syncthing is a continuous file synchronization program. It synchronizes files between two or more computers in real time."
            com.centurylinklabs.watchtower.enable: "true"
            com.docker.backup.restart-policy: unless-stopped
        healthcheck:
          test: ["CMD-SHELL", "wget --no-check-certificate --spider -q https://localhost:8384 || exit 1"]
          interval: 1m
          timeout: 10s
          retries: 3
volumes:    
    nginx_proxy_config:
        name: nginx_proxy_config
    nginx_proxy_letsencrypt:
        name: nginx_proxy_letsencrypt
    nginx_proxy_data:
        name: nginx_proxy_data
    adguard_work:
        name: adguard_work
    adguard_conf:
        name: adguard_conf    
    plex_server_config:
        name: plex_server_config
    plex_server_transcode:
        name: plex_server_transcode
    plex_server_media:
        name: plex_server_media
    syncthing_config:
        name: syncthing_config
networks:
    server_net:
        name: server_net
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1