version: "3.6"
name: base-portainer
services:
portainer:
    container_name: "portainer"
    image: "portainer/portainer-ce:2.21.5"
    ports:
      - "9443:9443/tcp"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost:9443 || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s